name       : python-kaptan
version    : 0.6.0
release    : 3
source     :
    - https://files.pythonhosted.org/packages/ca/c8/3569c90535df1b7c6079c75b7fd3f304d6ec8ee1626855d37ca137409ba2/kaptan-0.6.0.tar.gz : 101330a44fdede888586f3010bd145c0ec48a4806bc56429fa5487a6774021f8
license    : BSD-3-Clause
component  : programming.python
summary    : Configuration parser for Python
description: |
    Configuration parser for Python.
builddeps  :
    - python-pytest # Check
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
