name       : python-kaptan
version    : 0.5.12
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/k/kaptan/kaptan-0.5.12.tar.gz : 1abd1f56731422fce5af1acc28801677a51e56f5d3c3e8636db761ed143c3dd2
license    : BSD-3-Clause
component  : programming.python
summary    : Configuration parser for Python
description: |
    Configuration parser for Python.
builddeps  :
    - python-pytest # Check
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
